name: Linter and Telegram
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  build:
    name: Launch CSS linter
    runs-on: ubuntu-latest
    steps:
    - name: Send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TG_ID }}
        token: ${{ secrets.TG_TOKEN }}
        message: |
          ${{ github.actor }} Created new commit: ${{ github.event.commits[0].message }}
          Commit link: https://github.com/${{ github.repository }}/commit/${{github.sha}}
          Repo: https://github.com/${{ github.repository }}
            
          CI/CD github actions: https://github.com/${{ github.repository }}/actions
          https://github.com/${{ github.repository }}/actions/runs/${{github.run_id}}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Testing CSS linter
      uses: actions-hub/stylelint@master
      env:        
        PATTERN: "**/*.css"
